### PR TITLE
chore(travis): prevent 403 due to API rate limiting

### LINKED ISSUE #226: Travis is flaky
due to [403](https://travis-ci.org/angular/ts2dart/builds/68453950#L160)

is there anything we can do to improve the situation ?

/cc @mprobst

### PR DESCRIPTION
**Pull request by vicb**
fixes #226

see https://github.com/DefinitelyTyped/tsd#tsdrc

/cc @mprobst

[Review on Reviewable](https://reviewable.io/reviews/angular/ts2dart/228)

### CODE REVIEW

**Comment by mprobst** [comment]
Would you mind trying the environment variable `TSD_GITHUB_TOKEN ` first? Then we wouldn't need yet another dotfile; also this conceptually does belong to the travis configuration.

**Comment by vicb** [comment]
Updated. Thanks for the review + hint

**Comment by mprobst** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/ts2dart/228)

**Comment by mprobst** [comment]
LGTM.

**Pull request merged**
