### PR TITLE
feat(facade): add support for Map.delete(k)

### PR DESCRIPTION
**Pull request by vicb**
**THIS SHOULD NOT BE MERGED AS IS, THERE IS AN ERROR IN TESTS**

@mprobst I'm not sure to understand the error here, isn't it complaining about x not being typed ?

### CODE REVIEW

**Comment by mprobst** [comment]
@vicb the problem is that in our fake externs within `facade_converter_test.ts`, there is no declaration for `Map.delete`, and so the TypeScript type check fails. I should take a look and see why it doesn't give a proper error message.

The fix is to declare the `delete` method at the beginning of the file. Maybe just copy&paste everything from the Angular code base, this has bitten me before, too.

**Comment by vicb** [comment]
Thanks for the tip.

I had an other look and `JS.delete` returns whether the key was actually present, is it reasonable to convert `.delete` to an IIFE ?

**Comment by mprobst** [comment]
Should you be able to just return `myMap.containsKey(k) && (myMap.remove(k) != null || true)`? The latter will always be `true`, but with defined execution order it must always be executed, so together this returns whether `k` was in the map.

**Comment by vicb** [comment]
Nice trick !

**Comment by vicb** [comment]
PR update, PTAL.

**Comment by mprobst** [comment]
LGTM, please merge.

**Comment by vicb** [comment]
Thanks for the review

**Pull request merged**
