### PR TITLE
refactor(tests): use expectErroneousWithType()

### PR DESCRIPTION
**Pull request by vicb**
[Review on Reviewable](https://reviewable.io/reviews/angular/ts2dart/225)

### CODE REVIEW

**Comment by vicb** [comment]
Not sure what happens with clang-format. It want me to reformat literal.ts to align "//" comments. Is this something we really want ?

Also notes than Travis fails with 403 even after multiple trials (I've created a separate issue for that)

**Comment by mprobst** [comment]
LGTM if Travis is green (or confirmed only flaking).

**Comment by mprobst** [comment]
Regarding aligning line comments (`//`), I don't really care much, but I guess it can improve "scanability" of many end of line comments in a row. No idea why `literal.ts` isn't properly formatted though, maybe it's a versioning issue?

**Comment by vicb** [comment]
I see no reason to align eol comments (but I don't have anything strong against doing so).

The real question here is why clang-format is ok on Travis while it is not on my machine. This will cause troubles (when ok locally but not on Travis) and must be fixed

**Comment by vicb** [comment]
```
[15:00:23] WARNING: Files are not properly formatted. Please run
[15:00:23]   ./node_modules/gulp-clang-format/node_modules/clang-format/index.js -i -style="file" /home/victor/dart/ts2dart/lib/literal.ts
[15:00:24]   (using clang-format version 1.0.25)
[15:00:24] files not formatted
```

I'll merge this PR and create a separate issue to track this

**Comment by vicb** [comment]
landed as 25a38753066afb071ec0490348340d2bc016fe71

**Pull request closed without merging**
