### PR TITLE
fix(angular): don't rewrite relative paths to lib.d.ts

### LINKED ISSUE #314: relative path to stdlib changed
When we run latest ts2dart from angular, we don't convert the facade methods.
The facade_converter has a map from filename to the types we understand, one such filename is "lib"
with the current ts2dart we instead see "../../lib".
Looks like this was introduced in https://github.com/angular/ts2dart/commit/4ae749e597303b7606d647b23daed1463943bc59#diff-dfc2e8680f99b78f2e7d8c13b9a44855L249

I'm going to restore that conditional check to un-block angular. @vikerman this might break the g3 usage?

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #314

### CODE REVIEW

**Comment by alexeagle** [comment]
maybe this answers the question from #307

**Comment by IgorMinar** [comment]
lgtm

**Comment by IgorMinar** [comment]
we'll need to clean this up and bring back the changes after the next release. now we need to unblock https://github.com/angular/angular/pull/5758

**Comment by alexeagle** [comment]
Reverted two commits including cb6d27a51ba5cf99d50ff8b205fd8c9e1e0b68d4

**Pull request closed without merging**
